### ISSUE TITLE
Write project plan

### ISSUE THREAD

**Issue by heidi-holappa** [distro2024/distributed-chat-system#10]
Project goals: A lot of decision to be made
- [ ] define the architecture and roles of different nodes.
- [ ] Decide the middleware / communication mechanism to be used to pass messages between nodes
- [ ] (sockets, websockets, RPC, MessageQueue system, …).
- [ ] events: what are they and how do you know their ‘correct’ order
- [ ] How to handle global state, do you need logging or snapshots, what about recovery?
- [ ] Is there need for coordination, what about leader elections or some other consensus decisions
- [ ] What are you going to ensure data consistency?
- [ ] Are you going to have replication, where, when, how
- [ ] Start creating the design plan
